### ISSUE TITLE
It doesn't work at all...

### ISSUE THREAD

**Issue by LingleDev** [South-Paw/discord-music-bot#8]
Hey, I started using this musicbot today, and the commands do not work at all...

**Comment by South-Paw** [comment]
Hi there,

You will need to provide a lot more information than `It doesn't work at all...` and `the commands do not work at all` because currently this just looks like an issue created as a complaint.

You haven't provided anything useful for me to help you with such as setup info, any error logs you're seeing or any description of anything going wrong - just that you think it doesn't work.

If you can get back to me with some of that stuff I might be able to provide some help.

**Comment by LingleDev** [comment]
There isn't anything going wrong, the logs don't show anything.

**Comment by South-Paw** [comment]
Hi, I still don't understand what the issue is; what do you mean by the logs don't show anything?

**Comment by LingleDev** [comment]
When I start it, I try to use a command, and there's no reply, it doesn't
start playing, the logs don't show any errors, etc...

**Comment by South-Paw** [comment]
Could you please explain how you're starting it?

**Comment by LingleDev** [comment]
`node .`

**Comment by South-Paw** [comment]
So this isn't a bug or issue with the bot, you just don't know how to start it. Please refer to the readme for instructions on how to do so.

Thanks 👍

**Comment by LingleDev** [comment]
I do know how to start it. I'm a NodeJS bot developer, and I know darn good
and well... lol.
